before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy

env:
  - CGO_ENABLED=0
  - GO111MODULE=on

builds:
  - binary: SopsSecretGenerator
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

archives:
  - format: binary

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
