language: go

go:
  - 1.13.x

os:
  - linux

script:
  - make test-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/Library/Caches/go-build
    - $HOME/gopath/pkg/mod
